<?php

namespace Em\BackendBundle\Repository;


/**
 * AgencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencesRepository extends \Doctrine\ORM\EntityRepository
{

    public function  recupListeImmoByuser($user){
        $qb = $this->createQueryBuilder('a');
        $qb->select(array('a'));

        $qb->where('a.locked = :locked');
        $qb->andWhere('a.proprietaire = :proprietaire');
        $qb->andWhere('a.caracteristique = :appart');
        $qb->orWhere('a.caracteristique = :resid');
        $qb->setParameters(array('locked' => false, 'resid'=>'Residence', 'appart'=> 'Appartement' , 'proprietaire' => $user));
        $qb->orderBy('a.id' , 'DESC');
        return $qb->getQuery()->getResult();
    }
    public function  recupListeHotelByuser($user){
        $qb = $this->createQueryBuilder('a');
        $qb->select(array('a'));

        $qb->where('a.locked = :locked');
        $qb->andWhere('a.proprietaire = :proprietaire');
        $qb->andWhere('a.caracteristique = :hotel');
        $qb->setParameters(array('locked' => false, 'hotel'=>'Hotel','proprietaire' => $user));
        $qb->orderBy('a.id' , 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function recupListSend($User){
        $qb = $this->createQueryBuilder('f');
        $qb->select('a');
        $qb->where('a.hotelier = :hotelier');
        $qb->andWhere('a.hotelier = :hotelier');
        $qb->setParameters(array('hotelier' => $User , 'enabled' => true));
        $qb->orderBy('f.id', 'DESC');
        //  $qb->setMaxResults(13);

        return  $qb->getQuery()->getResult();
    }

    public function  reupAgenceGrade($grade){
        $qb = $this->createQueryBuilder('a');
        $qb->select('a');
        $qb->where('a.locked = :locked');
        $qb->andWhere('a.grade = :grade');
        $qb->setParameters(array('locked' => false, 'grade'=> $grade));
        $qb->orderBy('a.grade' , 'DESC');

        // var_dump($qb->getQuery()->getResult());die;
        return $qb->getQuery()->getResult();


    }


    //liste hotel
    public function  recupListeHotel(){
        $qb = $this->createQueryBuilder('a');
        $qb->select(array('a'));
      //  $qb->join('a.villes', 'v');
        $qb->where('a.locked = :locked');
       // $qb->andwhere('a.locked = :locked');
        $qb->setParameters(array('locked' => false));
        $qb->orderBy('a.grade' , 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function  recupListeHotelByCountry($entity){
        $qb = $this->createQueryBuilder('a');
        $qb->select(array('a'));
        $qb->join('a.villes', 'v');
        $qb->join('v.pays', 'p');
        $qb->where('a.locked = :locked');
         $qb->andwhere('p.id = :pays');
        $qb->setParameters(array('locked' => false, 'pays'=> $entity ));
        $qb->orderBy('a.grade' , 'DESC');
        return $qb->getQuery()->getResult();
    }
    //liste hotel par ville
   /* public function  recupAgencebyville($ville){
        $qb = $this->createQueryBuilder('a');
        $qb->select(array('a','v'));
        $qb->join('a.villes', 'v');
        $qb->where('a.locked = :locked');
        $qb->andwhere('a.locked = :locked');
        $qb->andwhere('v.slug = :slug');
        $qb->setParameters(array('locked' => false, 'slug' => $ville));
        $qb->orderBy('a.grade' , 'DESC');
        return $qb->getQuery()->getResult();
    }*/

    public function  recupAgencebyville($ville){
        $qb = $this->createQueryBuilder('a');
        $qb->select('a');
        $qb->where('a.locked = :locked');
        $qb->andwhere('a.locked = :locked')
         ->andWhere('a.ville LIKE :ville')
        ->setParameters(array('locked' => false, 'ville', '%"'.$ville.'"%'));
        $qb->orderBy('a.grade' , 'ASC');
        return $qb->getQuery()->getResult();
    }
    public function  findHomeSearch($location){
        $qb = $this->createQueryBuilder('b');
        $qb->select(array('b'));
        //* $qb->join('b.statusimmo', 's');
        //  $qb->join('b.typeimmo', 't');
        //  $qb->join('b.villes', 'v');
        $qb->where('b.locked = :locked');
        // $qb->andWhere('t.id = :typeimmo');
        $qb->andWhere('b.ville LIKE :ville');
        $qb->setParameters(
            array(
                'locked' => false,
                //     'typeimmo' => $type,
                'ville' => $location));
        $qb->orderBy('b.grade' , 'ASC');
        return $qb->getQuery()->getResult();
    }

    //Hotels
    public function  findHomeSearchCaracterisque($location, $caracteristique){
        $qb = $this->createQueryBuilder('b');
        $qb->select(array('b'));

        $qb->where('b.locked = :locked');
         $qb->andWhere('b.caracteristique = :caracteristique');
        $qb->andWhere('b.ville LIKE :ville');
        $qb->setParameters(
            array(
                'locked' => false,
                'caracteristique' => $caracteristique,
                'ville' => $location));
        $qb->orderBy('b.prixinit' , 'ASC');
        return $qb->getQuery()->getResult();
    }



    //liste hotel par ville
    public function  recupAgencebyprix($prix){
        $qb = $this->createQueryBuilder('a');
        $qb->select(array('a','v'));
        $qb->join('a.villes', 'v');
        $qb->where('a.locked = :locked');
        $qb->andwhere('a.locked = :locked');
        $qb->andwhere('a.prixinit = :prixinit');
        $qb->setParameters(array('locked' => false, 'prixinit' => $prix));
        $qb->orderBy('a.grade' , 'DESC');
        return $qb->getQuery()->getResult();
    }

    //liste hotel par commune
    public function  recupAgencebycommune($commune){
        $qb = $this->createQueryBuilder('a');
        $qb->select(array('a','c'));
        $qb->join('a.communes', 'c');
        $qb->where('a.locked = :locked');
        $qb->andwhere('a.locked = :locked');
        $qb->andwhere('c.slug = :slug');
        $qb->setParameters(array('locked' => false, 'slug' => $commune));
        $qb->orderBy('a.grade' , 'DESC');
        return $qb->getQuery()->getResult();
    }

    //liste hotel par etoile
    public function  recupAgencebyetoile($grade){
        $qb = $this->createQueryBuilder('a');
        $qb->select('a');
        $qb->where('a.locked = :locked');
        $qb->andwhere('a.grade = :grade');
        $qb->setParameters(array('locked' => false, 'grade' => $grade));
        $qb->orderBy('a.grade' , 'DESC');
        return $qb->getQuery()->getResult();
    }

}
