<?php

namespace Em\BackendBundle\Repository;

/**
 * CommunesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunesRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByVilleCommune($villecommune){
        $qb = $this->createQueryBuilder('c');
        $qb->select(array('c','v'));
        $qb->join('c.villes', 'v')
            ->where('v.nom LIKE :nom')
            ->setParameter('nom', '%'.$villecommune.'%');

        return  $qb->getQuery()->getResult();
    }
}
