<?php

namespace Em\BackendBundle\Repository;

/**
 * EtatimmoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatimmoRepository extends \Doctrine\ORM\EntityRepository
{
}
