<?php

namespace Em\BackendBundle\Repository;

/**
 * ImagesmultipleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesmultipleRepository extends \Doctrine\ORM\EntityRepository
{
}
