<?php

namespace Em\BackendBundle\Repository;

/**
 * ImagesmultiplechambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesmultiplechambreRepository extends \Doctrine\ORM\EntityRepository
{
}
