<?php

namespace Em\BackendBundle\Repository;

/**
 * ImagesmultipleimmoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesmultipleimmoRepository extends \Doctrine\ORM\EntityRepository
{
}
