<?php

namespace Em\BackendBundle\Repository;

/**
 * InformationsiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationsiteRepository extends \Doctrine\ORM\EntityRepository
{
}
