<?php

namespace Em\BackendBundle\Repository;

/**
 * PagesiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesiteRepository extends \Doctrine\ORM\EntityRepository
{
}
