<?php

namespace Em\BackendBundle\Repository;

/**
 * PubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubRepository extends \Doctrine\ORM\EntityRepository
{
    //page details hotel
    public function  pubActif(){
        $today = new \DateTime();

        $qb = $this->createQueryBuilder('p');
        $qb->select('p');
        $qb->where('p.datestart <= :datestart');
        $qb->andWhere('p.dateend >= :dateend');
        $qb->setParameters(array('datestart' => $today, 'dateend' => $today));

        return  $qb->getQuery()->getResult();
    }
}
