<?php

namespace Em\BackendBundle\Repository;

/**
 * StatusimmoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusimmoRepository extends \Doctrine\ORM\EntityRepository
{
}
