<?php

namespace Em\BackendBundle\Repository;

/**
 * TypeimmoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeimmoRepository extends \Doctrine\ORM\EntityRepository
{
}
