<?php

namespace Em\BackendBundle\Repository;

/**
 * TypesaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesaisonRepository extends \Doctrine\ORM\EntityRepository
{
}
