<?php

namespace Em\BackendBundle\Repository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRole($role)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->_entityName, 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"'.$role.'"%');

        return $qb->getQuery()->getResult();
    }

    public function findByRoleAndStatus($role, $status)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->_entityName, 'u')
            ->where('u.roles LIKE :roles')
            ->andWhere('u.enabled = :enabled')
            ->setParameters(array('roles'=> '%"'.$role.'"%', 'enabled' => $status))
            ->orderBy('u.id', 'DESC');


        return $qb->getQuery()->getResult();
    }

    public function findRoleUserAdmin($roleadmin)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->_entityName, 'u')
            ->where('u.roles LIKE :roles')
            ->setParameters(array('roles'=> '%"'.$roleadmin.'"%'))
            ->orderBy('u.id', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function verifUser($email){

        $qb = $this->createQueryBuilder('u');
        $qb->select('COUNT(u)');
        $qb->where('u.email = :email');
        $qb->setParameter('email', $email);

        return   $count = $qb->getQuery()->getSingleScalarResult();
    }
    public function verifUserAndRole($email,$role){

        $qb = $this->createQueryBuilder('u');
        $qb->select('COUNT(u)');
        $qb->where('u.email = :email');
        $qb->andWhere('u.roles LIKE :roles');
        $qb->setParameters(array('email'=> $email,'roles'=> '%"'.$role.'"%' ));

        return   $count = $qb->getQuery()->getSingleScalarResult();
    }
}
