<?php

namespace Em\FrontendBundle\Repository;

/**
 * AllFonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllFonctionRepository extends \Doctrine\ORM\EntityRepository
{
    //Cette class va servir de verification
    // date
    //prix
   public function buffer($mois)
   {

       $databuffer = array(0);
       $months = array("Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre");
       $monthsShort = array("Jan", "Fev", "Mar", "Avr", "Mai", "Jui", "Jui", "Aou", "Sep", "Oct", "Nov", "Dec");

     if (in_array($mois, $months) || in_array($mois, $monthsShort)) {
         if ($mois == "Avril" || $mois == "Avr" || $mois == 'Novembre' || $mois == 'Nov' || $mois == "Juin" || $mois == "Jui" ||  $mois == 'Septembre' || $mois == 'Sep') {

             $databuffer['mois'] = 30;
         }
         elseif ($mois == "Janvier" || $mois == "Jan" || $mois == 'Mars' || $mois == 'Mar'
             || $mois == "Mai" || $mois == "Mai" || $mois == 'Juillet' || $mois == 'Jui' || $mois == 'Aout'|| $mois == 'Aou'
             || $mois == 'Octobre'|| $mois == 'Oct'|| $mois == 'Decembre'|| $mois == 'Dec') {

             $databuffer['mois'] = 31;

         }elseif($mois == "Fevrier" || $mois == "Fev"){
             $databuffer['mois'] = 28;
         }


      }

       return $databuffer ;
    }

    public function verifFormatDate($format){

        //
        $dataarray = array();
        $styleform = explode($format, ',');
        if(isset($styleform[0])){

            $style = explode($styleform, ' ');
            if(is_array($style)){

                $dataarray['jour'] = $style[1];
                $dataarray['mois'] = $this->buffer($style[0]) ;
                return $dataarray ;

            }else{
                return null;
            }

        }
    }
    public function verfiDateCalscul($datestart, $dateend){

        $start = $this->verifFormatDate($datestart);
        $end = $this->verifFormatDate($dateend);

        //on va verifier la validité du mois
        // cette verification permettra de faire un calcul sur les dates
        // exemple 28 Mars - 02 Avril




        if($start['jour']  != null and $end['jour'] != null){

            //si le nombre de jour final est inferieur
            if($end['jour'] < $start['jour']  ){
                $end['jour'] = $end['jour'] + $end['mois'];
            }

             return  $nbsejour = $end['jour'] - $start['jour'];
        }else{

            return false;
        }
    }

    public function calculPrix($datestart, $dateend, $prix){
           $nbsejour = $this->verfiDateCalscul($datestart, $dateend);
           $newsprix = 0;

           if($nbsejour){
               $newsprix = (int) $prix * $nbsejour;
           }

        return $newsprix;

    }


}
