<?php

namespace Em\FrontendBundle\Repository;

/**
 * ReservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function calculallSum(){
        $qb = $this->createQueryBuilder('r');
        $qb->select('SUM(r.prixtotal) AS somtotal ');
        $qb->where('r.confirmer = :confirmer');
        $qb->setParameter('confirmer' , true);

        return  $qb->getQuery()->getSingleResult();
    }

    public function findReservationBYHotelier($user){

        $qb = $this->createQueryBuilder('r');
        $qb->select('r');
        $qb->join('r.proprietaire', 'p');
        $qb->where('r.confirmer = :confirmer');
        $qb->andWhere('p.id= :prop');
        $qb->setParameters(array('confirmer' => true, 'prop' => $user->getId()));
        $qb->orderBy('r.id' , 'desc');
        return  $qb->getQuery()->getResult();
    }

    public function findAgenceBYUser($email){
        $qb = $this->createQueryBuilder('r');
        $qb->join('r.chambre', 'c');
        $qb->leftJoin('c.agences', 'a');



      //  $qb->where('r.confirmer = :confirmer');
        $qb->where('r.email = :email');

        //$qb->setParameters(array('confirmer' => true, 'email' => $email));
        $qb->setParameter('email', $email);


        return  $qb->getQuery()->getResult();
    }



    public function findByCode($code){
        $qb = $this->createQueryBuilder('r');
        $qb->select('r.numeroreservation')
            ->where('r.numeroreservation LIKE :numeroreservation')
            ->setParameter('numeroreservation', '%'.$code.'%');

        return  $qb->getQuery()->getResult();
    }
}
